In [2]:
!mamba install pandas

mambajs 0.21.4

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 0.628 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.6    np23py313h124dbc7_0  emscripten-forge-4x
+ python-tzdata  2026.3   pyhd8ed1ab_0         conda-forge
- pip            26.2.1   pyh145f28c_0         conda-forge

In [13]:
import pandas as pd

In [14]:
df = pd.read_csv("exercise_dataset.csv")

In [15]:
df.head()

,ID,Exercise,Calories Burn,Dream Weight,Actual Weight,Age,Gender,Duration,Heart Rate,BMI,Weather Conditions,Exercise Intensity
0,1,Exercise 2,286.959851,91.892531,96.301115,45,Male,37,170,29.426275,Rainy,5
1,2,Exercise 7,343.453036,64.165097,61.104668,25,Male,43,142,21.286346,Rainy,5
2,3,Exercise 4,261.223465,70.846224,71.766724,20,Male,20,148,27.899592,Cloudy,4
3,4,Exercise 5,127.183858,79.477008,82.984456,33,Male,39,170,33.729552,Sunny,10
4,5,Exercise 10,416.318374,89.960226,85.643174,29,Female,34,118,23.286113,Cloudy,3

In [16]:
df["Calories Burn"] = pd.to_numeric(df["Calories Burn"], errors="coerce")

df = df.dropna(subset=["Calories Burn", "Exercise"])

df.head()

,ID,Exercise,Calories Burn,Dream Weight,Actual Weight,Age,Gender,Duration,Heart Rate,BMI,Weather Conditions,Exercise Intensity
0,1,Exercise 2,286.959851,91.892531,96.301115,45,Male,37,170,29.426275,Rainy,5
1,2,Exercise 7,343.453036,64.165097,61.104668,25,Male,43,142,21.286346,Rainy,5
2,3,Exercise 4,261.223465,70.846224,71.766724,20,Male,20,148,27.899592,Cloudy,4
3,4,Exercise 5,127.183858,79.477008,82.984456,33,Male,39,170,33.729552,Sunny,10
4,5,Exercise 10,416.318374,89.960226,85.643174,29,Female,34,118,23.286113,Cloudy,3

In [17]:
df["Exercise"].unique()

<StringArray>
[ 'Exercise 2',  'Exercise 7',  'Exercise 4',  'Exercise 5', 'Exercise 10',
  'Exercise 1',  'Exercise 9',  'Exercise 8',  'Exercise 6',  'Exercise 3']
Length: 10, dtype: str

In [18]:
def workout_percentile(exercise, calories):
    
    workouts = df[df["Exercise"] == exercise]["Calories Burn"]
    
    percentile = (workouts < calories).mean() * 100
    
    return percentile

In [19]:
print("Workout Percentile Calculator")
print()

print("Exercises available:")
for exercise in df["Exercise"].unique():
    print("-", exercise)

exercise = input("\nEnter your exercise exactly as shown above: ")

calories = float(input("How many calories did you burn? "))

result = workout_percentile(exercise, calories)

print()
print(f"Your workout burned more calories than {result:.1f}% of {exercise} workouts in the dataset.")

Workout Percentile Calculator

Exercises available:
- Exercise 2
- Exercise 7
- Exercise 4
- Exercise 5
- Exercise 10
- Exercise 1
- Exercise 9
- Exercise 8
- Exercise 6
- Exercise 3

Enter your exercise exactly as shown above:  Exercise 4
How many calories did you burn?  430

Your workout burned more calories than 77.4% of Exercise 4 workouts in the dataset.